# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 10:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acad_Year', models.IntegerField(default=2018)),
                ('Acad_Month', models.IntegerField(default=4)),
                ('Entry_Time', models.DateTimeField(blank=True, null=True)),
                ('Exit_Time', models.DateTimeField(blank=True, null=True)),
                ('Total_Time_Spent', models.IntegerField(blank=True, null=True)),
                ('LeaveApplied', models.BooleanField(default=None)),
                ('LeaveType', models.CharField(choices=[('cl', 'Casual Leave'), ('ccl', 'Compensatory Casual Leave'), ('od', 'On Duty'), ('defult', '')], default='default', max_length=6)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('EmployeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=50)),
                ('DateofBirth', models.DateField()),
                ('OriginalDoB', models.DateField()),
                ('JoiningDate', models.DateField()),
                ('TotalExperience_inYears', models.FloatField()),
                ('TotalExperience_inAditya_inYears', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('About', models.TextField(blank=True, null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Image', models.ImageField(upload_to=b'')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acad_Year', models.IntegerField(default=2018)),
                ('Acad_Month', models.IntegerField(default=4)),
                ('WorkingDays', models.IntegerField()),
                ('AttendedDays', models.IntegerField()),
                ('CL_available', models.IntegerField()),
                ('CL_Used', models.IntegerField()),
                ('CCL_available', models.IntegerField()),
                ('CCL_Used', models.IntegerField()),
                ('OD_Used', models.IntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thub_Attendance.EmployeeDetails')),
            ],
        ),
        migrations.AddField(
            model_name='employeedailyreport',
            name='EmpID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thub_Attendance.EmployeeDetails'),
        ),
    ]
